# Generated by Django 6.0.4 on 2026-04-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_alter_evento_options_alter_inscricao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Local do Evento'),
        ),
    ]
