# Generated by Django 6.0.4 on 2026-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntapersonalizada',
            name='evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='questionario',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tem_questionario',
            field=models.BooleanField(default=False, verbose_name='Habilitar questionário extra?'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='respostas_questionario',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='OpcaoPergunta',
        ),
        migrations.DeleteModel(
            name='PerguntaPersonalizada',
        ),
    ]
