# Generated by Django 6.0.4 on 2026-05-08 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_remove_perguntapersonalizada_evento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Oficina de Python (Engloba Turma Manhã e Turma Tarde)', max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Grupo de Evento',
                'verbose_name_plural': 'Grupos de Eventos',
            },
        ),
        migrations.AddField(
            model_name='evento',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Selecione um grupo se este evento tiver outras turmas/horários correlacionados.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='eventos.grupoevento'),
        ),
    ]
