# Generated by Django 6.0.4 on 2026-05-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_grupoevento_evento_grupo'),
        ('eventos', '0006_cria_grupo_avaliadores'),
    ]

    operations = [
    ]
