# Generated by Django 6.0.4 on 2026-06-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_inscricao_compareceu_inscricao_inscricao_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='frequencia_minima',
            field=models.PositiveIntegerField(default=75, verbose_name='Frequência Mínima (%) para Certificado'),
        ),
        migrations.AddField(
            model_name='evento',
            name='total_sessoes',
            field=models.PositiveIntegerField(default=1, verbose_name='Total de Dias/Sessões'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='total_presencas',
            field=models.PositiveIntegerField(default=0, verbose_name='Total de Presenças'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ultimo_checkin',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Check-in'),
        ),
    ]
