# Generated by Django 6.0.4 on 2026-06-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_alter_inscricao_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aplica_restricao_faltas',
            field=models.BooleanField(default=False, help_text='Se ativado, inscritos que faltaram em eventos passados vão automaticamente para a fila de espera.', verbose_name='Aplicar Política de Faltas'),
        ),
    ]
