# Generated by Django 6.0.4 on 2026-06-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_evento_aplica_restricao_faltas'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleNoShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('nome', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(choices=[('PERDAO', 'Perdoado (Ignora Faltas Automáticas)'), ('BLOQUEIO', 'Bloqueado Manualmente')], max_length=15)),
                ('justificativa', models.TextField(blank=True, help_text='Motivo do perdão ou bloqueio', null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
