# Generated by Django 6.0.4 on 2026-06-27 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0013_controlenoshow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='controlenoshow',
            options={'verbose_name': 'Controle de Faltosos', 'verbose_name_plural': 'Controle de Faltosos'},
        ),
    ]
