# Generated by Django 6.0.4 on 2026-09-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0014_alter_controlenoshow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='permite_inscricao_local',
            field=models.BooleanField(default=True, help_text='Se ativado, pessoas não inscritas poderão se cadastrar escaneando o QR Code na porta.', verbose_name='Permitir Inscrições na Hora'),
        ),
    ]
