# Generated by Django 6.0.4 on 2026-04-27 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem_capa', models.ImageField(blank=True, null=True, upload_to='capas_eventos/')),
                ('vagas_totais', models.PositiveIntegerField()),
                ('aberto_comunidade', models.BooleanField(default=False, verbose_name='Aberto à comunidade externa?')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('tem_vinculo_universidade', models.BooleanField(default=True)),
                ('matricula', models.CharField(blank=True, max_length=50, null=True)),
                ('curso_turma', models.CharField(blank=True, max_length=100, null=True)),
                ('trabalho', models.CharField(blank=True, max_length=255, null=True)),
                ('orientador', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('APROVADA', 'Aprovada'), ('RECUSADA', 'Recusada'), ('LISTA_ESPERA', 'Lista de Espera')], default='PENDENTE', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='eventos.evento')),
            ],
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_opcao', models.CharField(max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='eventos.perguntapersonalizada')),
            ],
        ),
    ]
