# Generated by Django 6.0.4 on 2026-04-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='inscricao',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AddField(
            model_name='evento',
            name='fim_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Fim das Inscrições'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inicio_inscricoes',
            field=models.DateTimeField(null=True, verbose_name='Início das Inscrições'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(verbose_name='Término do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_inicio',
            field=models.DateTimeField(verbose_name='Início do Evento'),
        ),
    ]
