# Generated by Django 6.0.4 on 2026-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_merge_20260508_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='aprovacao_automatica',
            field=models.BooleanField(default=False, help_text='Se ativado, os inscritos serão aprovados automaticamente ao enviarem o formulário.', verbose_name='Aprovação Automática'),
        ),
    ]
