# Generated by Django 6.0.4 on 2026-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_evento_aprovacao_automatica'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='compareceu',
            field=models.BooleanField(default=False, verbose_name='Check-in Realizado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_local',
            field=models.BooleanField(default=False, verbose_name='Inscrito na Hora'),
        ),
    ]
