# Generated by Django 6.0.4 on 2026-06-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0010_evento_frequencia_minima_evento_total_sessoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='cpf',
            field=models.CharField(db_index=True, max_length=14),
        ),
    ]
